name = "BossLandCreate2"
author = "ArAf"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa7f27c37d530a8e90e9d158491e3abbf667da4c52b886f5454308b6a8de89ba"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
