name = "BossLandCreate2"
author = "ArAf"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29623e09aa55ff54f862d532fab184fa7182cb6ca2769b20299bc60fc4d8006e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
