name = "BossLandCreate2"
author = "ArAf"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9ea6e8a8dd86db1c352c88ef323c056ee153f9f2c0bfc087b89bf2864d9dde8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
